# To see apps name: swaymsg -t get_tree
# For icons:
# - https://fontawesome.com/icons
# - https://www.nerdfonts.com/cheat-sheet

fallback = ''
separator = ' '

[matching]
'firefox' = '󰈹' # Arch
'Firefox' = '󰈹' # Debian
'chromium' = '' # Debian
'/\w* - Nvim/' = ''
'/NeoMutt/' = ''
'org.gnome.Nautilus' = ''
'org.keepassxc.KeePassXC' = ''
'KeePassXC' = ''
'imv' = ''
'mpv' = '󰐌'
'wdisplays' = ''
'gimp' = ''
'org.pwmt.zathura' = ''
'libreoffice-calc' = ''
'libreoffice-writer' = ''
'steam' = '󰓓'
